# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(929, 566)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        brush1 = QBrush(QColor(238, 238, 236, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setFamily(u"Bitstream Vera Sans Mono")
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u"src/modbus/modbus/picture/teco_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(20, 110, 181, 381))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.btn_reset = QPushButton(self.verticalLayoutWidget)
        self.btn_reset.setObjectName(u"btn_reset")
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush2 = QBrush(QColor(218, 119, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_reset.setPalette(palette1)
        font1 = QFont()
        font1.setFamily(u"Bitstream Vera Sans")
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setWeight(75)
        self.btn_reset.setFont(font1)
        self.btn_reset.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.btn_reset)

        self.btn_enable = QPushButton(self.verticalLayoutWidget)
        self.btn_enable.setObjectName(u"btn_enable")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush3 = QBrush(QColor(0, 210, 26, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.btn_enable.setPalette(palette2)
        self.btn_enable.setFont(font1)
        self.btn_enable.setStyleSheet(u"background-color:#00d21a;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.btn_enable)

        self.btn_disable = QPushButton(self.verticalLayoutWidget)
        self.btn_disable.setObjectName(u"btn_disable")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush4 = QBrush(QColor(177, 0, 17, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush4)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush4)
        self.btn_disable.setPalette(palette3)
        self.btn_disable.setFont(font1)
        self.btn_disable.setStyleSheet(u"background-color:#b10011;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.btn_disable)

        self.onBtn = QPushButton(self.verticalLayoutWidget)
        self.onBtn.setObjectName(u"onBtn")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.onBtn.setPalette(palette4)
        self.onBtn.setFont(font1)
        self.onBtn.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.onBtn)

        self.offBtn = QPushButton(self.verticalLayoutWidget)
        self.offBtn.setObjectName(u"offBtn")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.offBtn.setPalette(palette5)
        self.offBtn.setFont(font1)
        self.offBtn.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")

        self.verticalLayout.addWidget(self.offBtn)

        self.gridLayoutWidget_2 = QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 10, 201, 94))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.lineEdit_ip = QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_ip.setObjectName(u"lineEdit_ip")

        self.gridLayout_2.addWidget(self.lineEdit_ip, 2, 0, 1, 1)

        self.label_ip = QLabel(self.gridLayoutWidget_2)
        self.label_ip.setObjectName(u"label_ip")
        font2 = QFont()
        font2.setFamily(u"Bitstream Vera Sans")
        font2.setBold(True)
        font2.setWeight(75)
        self.label_ip.setFont(font2)

        self.gridLayout_2.addWidget(self.label_ip, 0, 0, 1, 1)

        self.btn_ip_set = QPushButton(self.gridLayoutWidget_2)
        self.btn_ip_set.setObjectName(u"btn_ip_set")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush5 = QBrush(QColor(0, 86, 239, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush5)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush5)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush5)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush5)
        self.btn_ip_set.setPalette(palette6)
        self.btn_ip_set.setFont(font1)
        self.btn_ip_set.setStyleSheet(u"background-color:#0056ef;color:white;border-color: black;")

        self.gridLayout_2.addWidget(self.btn_ip_set, 3, 0, 1, 1)

        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(220, 10, 691, 501))
        font3 = QFont()
        font3.setFamily(u"Bitstream Vera Sans Mono")
        font3.setBold(True)
        font3.setWeight(75)
        self.tabWidget.setFont(font3)
        self.tabWidget.setTabShape(QTabWidget.Triangular)
        self.tab_arm = QWidget()
        self.tab_arm.setObjectName(u"tab_arm")
        self.verticalLayoutWidget_3 = QWidget(self.tab_arm)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 10, 671, 431))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_acs_command_list = QLabel(self.verticalLayoutWidget_3)
        self.label_acs_command_list.setObjectName(u"label_acs_command_list")
        font4 = QFont()
        font4.setPointSize(15)
        font4.setBold(True)
        font4.setWeight(75)
        self.label_acs_command_list.setFont(font4)
        self.label_acs_command_list.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_acs_command_list)

        self.tableView_joint = QTableView(self.verticalLayoutWidget_3)
        self.tableView_joint.setObjectName(u"tableView_joint")
        font5 = QFont()
        font5.setPointSize(13)
        self.tableView_joint.setFont(font5)
        self.tableView_joint.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableView_joint.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_3.addWidget(self.tableView_joint)

        self.label_pcs_command_list = QLabel(self.verticalLayoutWidget_3)
        self.label_pcs_command_list.setObjectName(u"label_pcs_command_list")
        self.label_pcs_command_list.setFont(font4)
        self.label_pcs_command_list.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_pcs_command_list)

        self.tableView_pos = QTableView(self.verticalLayoutWidget_3)
        self.tableView_pos.setObjectName(u"tableView_pos")
        self.tableView_pos.setFont(font5)
        self.tableView_pos.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableView_pos.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_3.addWidget(self.tableView_pos)

        self.tabWidget.addTab(self.tab_arm, "")
        self.tab_mission = QWidget()
        self.tab_mission.setObjectName(u"tab_mission")
        self.gridLayoutWidget = QWidget(self.tab_mission)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(30, 290, 381, 151))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.label_mission_case_show = QLabel(self.gridLayoutWidget)
        self.label_mission_case_show.setObjectName(u"label_mission_case_show")

        self.gridLayout.addWidget(self.label_mission_case_show, 2, 1, 1, 1)

        self.label_mission_case = QLabel(self.gridLayoutWidget)
        self.label_mission_case.setObjectName(u"label_mission_case")

        self.gridLayout.addWidget(self.label_mission_case, 2, 0, 1, 1)

        self.comboBox = QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName(u"comboBox")

        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)

        self.btn_start_program = QPushButton(self.gridLayoutWidget)
        self.btn_start_program.setObjectName(u"btn_start_program")
        self.btn_start_program.setFont(font5)
        self.btn_start_program.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")

        self.gridLayout.addWidget(self.btn_start_program, 0, 1, 1, 1)

        self.btn_stop_program = QPushButton(self.gridLayoutWidget)
        self.btn_stop_program.setObjectName(u"btn_stop_program")
        font6 = QFont()
        font6.setPointSize(13)
        font6.setBold(True)
        font6.setWeight(75)
        self.btn_stop_program.setFont(font6)
        self.btn_stop_program.setStyleSheet(u"background-color:#005b62;color:white;border-color: black;")

        self.gridLayout.addWidget(self.btn_stop_program, 1, 1, 1, 1)

        self.groupBox_speed = QGroupBox(self.tab_mission)
        self.groupBox_speed.setObjectName(u"groupBox_speed")
        self.groupBox_speed.setGeometry(QRect(30, 90, 371, 171))
        palette7 = QPalette()
        brush6 = QBrush(QColor(173, 127, 168, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush6)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush)
        brush7 = QBrush(QColor(193, 125, 17, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush1)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        self.groupBox_speed.setPalette(palette7)
        self.groupBox_speed.setFont(font5)
        self.groupBox_speed.setAlignment(Qt.AlignCenter)
        self.horizontalSlider_acc = QSlider(self.groupBox_speed)
        self.horizontalSlider_acc.setObjectName(u"horizontalSlider_acc")
        self.horizontalSlider_acc.setGeometry(QRect(10, 100, 160, 16))
        self.horizontalSlider_acc.setStyleSheet(u"")
        self.horizontalSlider_acc.setMaximum(100)
        self.horizontalSlider_acc.setOrientation(Qt.Horizontal)
        self.btn_acc_set = QPushButton(self.groupBox_speed)
        self.btn_acc_set.setObjectName(u"btn_acc_set")
        self.btn_acc_set.setGeometry(QRect(270, 90, 81, 25))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush)
        palette8.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette8.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette8.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_acc_set.setPalette(palette8)
        self.btn_acc_set.setFont(font5)
        self.btn_acc_set.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.lineEdit_acc = QLineEdit(self.groupBox_speed)
        self.lineEdit_acc.setObjectName(u"lineEdit_acc")
        self.lineEdit_acc.setGeometry(QRect(180, 90, 81, 25))
        self.btn_vel_set = QPushButton(self.groupBox_speed)
        self.btn_vel_set.setObjectName(u"btn_vel_set")
        self.btn_vel_set.setGeometry(QRect(270, 40, 81, 25))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_vel_set.setPalette(palette9)
        self.btn_vel_set.setFont(font5)
        self.btn_vel_set.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.lineEdit_vel = QLineEdit(self.groupBox_speed)
        self.lineEdit_vel.setObjectName(u"lineEdit_vel")
        self.lineEdit_vel.setGeometry(QRect(180, 40, 81, 25))
        self.horizontalSlider_vel = QSlider(self.groupBox_speed)
        self.horizontalSlider_vel.setObjectName(u"horizontalSlider_vel")
        self.horizontalSlider_vel.setGeometry(QRect(10, 50, 160, 16))
        self.horizontalSlider_vel.setStyleSheet(u"")
        self.horizontalSlider_vel.setMaximum(100)
        self.horizontalSlider_vel.setOrientation(Qt.Horizontal)
        self.label_velocity = QLabel(self.groupBox_speed)
        self.label_velocity.setObjectName(u"label_velocity")
        self.label_velocity.setGeometry(QRect(20, 30, 121, 17))
        self.label_velocity.setAlignment(Qt.AlignCenter)
        self.label_acceleration = QLabel(self.groupBox_speed)
        self.label_acceleration.setObjectName(u"label_acceleration")
        self.label_acceleration.setGeometry(QRect(20, 80, 141, 17))
        self.label_acceleration.setAlignment(Qt.AlignCenter)
        self.btn_vel_slow_set = QPushButton(self.groupBox_speed)
        self.btn_vel_slow_set.setObjectName(u"btn_vel_slow_set")
        self.btn_vel_slow_set.setGeometry(QRect(20, 130, 151, 29))
        self.btn_vel_slow_set.setFont(font5)
        self.btn_vel_slow_set.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")
        self.btn_vel_quick_set = QPushButton(self.groupBox_speed)
        self.btn_vel_quick_set.setObjectName(u"btn_vel_quick_set")
        self.btn_vel_quick_set.setGeometry(QRect(190, 130, 151, 29))
        self.btn_vel_quick_set.setFont(font5)
        self.btn_vel_quick_set.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")
        self.label_project_name = QLabel(self.tab_mission)
        self.label_project_name.setObjectName(u"label_project_name")
        self.label_project_name.setGeometry(QRect(20, 20, 351, 17))
        self.label_project_name.setFont(font5)
        self.label_project_name.setAlignment(Qt.AlignCenter)
        self.lineEdit_project_name_select = QLineEdit(self.tab_mission)
        self.lineEdit_project_name_select.setObjectName(u"lineEdit_project_name_select")
        self.lineEdit_project_name_select.setGeometry(QRect(20, 50, 251, 25))
        self.btn_project_name_select = QPushButton(self.tab_mission)
        self.btn_project_name_select.setObjectName(u"btn_project_name_select")
        self.btn_project_name_select.setGeometry(QRect(370, 50, 81, 25))
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Text, brush)
        palette10.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_project_name_select.setPalette(palette10)
        self.btn_project_name_select.setFont(font5)
        self.btn_project_name_select.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.btn_project_name_read = QPushButton(self.tab_mission)
        self.btn_project_name_read.setObjectName(u"btn_project_name_read")
        self.btn_project_name_read.setGeometry(QRect(280, 50, 81, 25))
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Text, brush)
        palette11.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.btn_project_name_read.setPalette(palette11)
        self.btn_project_name_read.setFont(font5)
        self.btn_project_name_read.setStyleSheet(u"background-color:#da7700;color:white;border-color: black;")
        self.verticalLayoutWidget_5 = QWidget(self.tab_mission)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(490, 0, 160, 461))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.btn_show_program = QPushButton(self.verticalLayoutWidget_5)
        self.btn_show_program.setObjectName(u"btn_show_program")
        font7 = QFont()
        font7.setPointSize(15)
        self.btn_show_program.setFont(font7)
        self.btn_show_program.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")

        self.verticalLayout_5.addWidget(self.btn_show_program)

        self.btn_dance_program = QPushButton(self.verticalLayoutWidget_5)
        self.btn_dance_program.setObjectName(u"btn_dance_program")
        self.btn_dance_program.setFont(font7)
        self.btn_dance_program.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")

        self.verticalLayout_5.addWidget(self.btn_dance_program)

        self.btn_smile_program = QPushButton(self.verticalLayoutWidget_5)
        self.btn_smile_program.setObjectName(u"btn_smile_program")
        self.btn_smile_program.setFont(font7)
        self.btn_smile_program.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")

        self.verticalLayout_5.addWidget(self.btn_smile_program)

        self.btn_bow_program = QPushButton(self.verticalLayoutWidget_5)
        self.btn_bow_program.setObjectName(u"btn_bow_program")
        self.btn_bow_program.setFont(font7)
        self.btn_bow_program.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")

        self.verticalLayout_5.addWidget(self.btn_bow_program)

        self.btn_init_program = QPushButton(self.verticalLayoutWidget_5)
        self.btn_init_program.setObjectName(u"btn_init_program")
        self.btn_init_program.setFont(font4)
        self.btn_init_program.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")

        self.verticalLayout_5.addWidget(self.btn_init_program)

        self.btn_home_program = QPushButton(self.verticalLayoutWidget_5)
        self.btn_home_program.setObjectName(u"btn_home_program")
        self.btn_home_program.setFont(font4)
        self.btn_home_program.setStyleSheet(u"background-color:#0300fc;color:white;border-color: black;")

        self.verticalLayout_5.addWidget(self.btn_home_program)

        self.btn_stopshow_program = QPushButton(self.verticalLayoutWidget_5)
        self.btn_stopshow_program.setObjectName(u"btn_stopshow_program")
        self.btn_stopshow_program.setFont(font4)
        self.btn_stopshow_program.setStyleSheet(u"background-color:#005b62;color:white;border-color: black;")

        self.verticalLayout_5.addWidget(self.btn_stopshow_program)

        self.tabWidget.addTab(self.tab_mission, "")
        self.tab_state = QWidget()
        self.tab_state.setObjectName(u"tab_state")
        self.verticalLayoutWidget_4 = QWidget(self.tab_state)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(10, 10, 351, 431))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_rostopic_pub_list = QLabel(self.verticalLayoutWidget_4)
        self.label_rostopic_pub_list.setObjectName(u"label_rostopic_pub_list")
        font8 = QFont()
        font8.setPointSize(14)
        font8.setBold(True)
        font8.setWeight(75)
        self.label_rostopic_pub_list.setFont(font8)

        self.verticalLayout_4.addWidget(self.label_rostopic_pub_list)

        self.tableView_pub = QTableView(self.verticalLayoutWidget_4)
        self.tableView_pub.setObjectName(u"tableView_pub")
        self.tableView_pub.setFont(font5)
        self.tableView_pub.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableView_pub.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_4.addWidget(self.tableView_pub)

        self.label_rostopic_echo_list = QLabel(self.verticalLayoutWidget_4)
        self.label_rostopic_echo_list.setObjectName(u"label_rostopic_echo_list")
        self.label_rostopic_echo_list.setFont(font8)

        self.verticalLayout_4.addWidget(self.label_rostopic_echo_list)

        self.tableView_echo = QTableView(self.verticalLayoutWidget_4)
        self.tableView_echo.setObjectName(u"tableView_echo")
        self.tableView_echo.setFont(font5)
        self.tableView_echo.setSelectionMode(QAbstractItemView.MultiSelection)
        self.tableView_echo.setSelectionBehavior(QAbstractItemView.SelectRows)

        self.verticalLayout_4.addWidget(self.tableView_echo)

        self.tabWidget.addTab(self.tab_state, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.btn_test = QPushButton(self.tab)
        self.btn_test.setObjectName(u"btn_test")
        self.btn_test.setGeometry(QRect(480, 60, 179, 33))
        palette12 = QPalette()
        brush8 = QBrush(QColor(0, 0, 0, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        brush9 = QBrush(QColor(233, 185, 110, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette12.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette12.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        brush10 = QBrush(QColor(190, 190, 190, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette12.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette12.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        self.btn_test.setPalette(palette12)
        self.btn_test.setFont(font1)
        self.btn_test2 = QPushButton(self.tab)
        self.btn_test2.setObjectName(u"btn_test2")
        self.btn_test2.setGeometry(QRect(480, 120, 179, 33))
        palette13 = QPalette()
        palette13.setBrush(QPalette.Active, QPalette.WindowText, brush8)
        palette13.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette13.setBrush(QPalette.Inactive, QPalette.WindowText, brush8)
        palette13.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette13.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette13.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        self.btn_test2.setPalette(palette13)
        self.btn_test2.setFont(font1)
        self.gridLayoutWidget_3 = QWidget(self.tab)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(30, 10, 321, 451))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.btn_b_positive = QPushButton(self.gridLayoutWidget_3)
        self.btn_b_positive.setObjectName(u"btn_b_positive")
        palette14 = QPalette()
        palette14.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush11 = QBrush(QColor(0, 48, 96, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette14.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette14.setBrush(QPalette.Active, QPalette.Text, brush)
        palette14.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette14.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette14.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette14.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette14.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette14.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette14.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_b_positive.setPalette(palette14)
        self.btn_b_positive.setFont(font5)
        self.btn_b_positive.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_b_positive, 7, 0, 1, 1)

        self.btn_z_positive = QPushButton(self.gridLayoutWidget_3)
        self.btn_z_positive.setObjectName(u"btn_z_positive")
        palette15 = QPalette()
        palette15.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette15.setBrush(QPalette.Active, QPalette.Text, brush)
        palette15.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette15.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette15.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette15.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette15.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette15.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette15.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette15.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette15.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_z_positive.setPalette(palette15)
        self.btn_z_positive.setFont(font5)
        self.btn_z_positive.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_z_positive, 5, 0, 1, 1)

        self.btn_x_negative = QPushButton(self.gridLayoutWidget_3)
        self.btn_x_negative.setObjectName(u"btn_x_negative")
        palette16 = QPalette()
        palette16.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette16.setBrush(QPalette.Active, QPalette.Text, brush)
        palette16.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette16.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette16.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette16.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette16.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette16.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette16.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette16.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette16.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette16.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette16.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_x_negative.setPalette(palette16)
        self.btn_x_negative.setFont(font5)
        self.btn_x_negative.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_x_negative, 4, 1, 1, 1)

        self.btn_a_positive = QPushButton(self.gridLayoutWidget_3)
        self.btn_a_positive.setObjectName(u"btn_a_positive")
        palette17 = QPalette()
        palette17.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette17.setBrush(QPalette.Active, QPalette.Text, brush)
        palette17.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette17.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette17.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette17.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette17.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette17.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette17.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette17.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette17.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_a_positive.setPalette(palette17)
        self.btn_a_positive.setFont(font5)
        self.btn_a_positive.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_a_positive, 6, 0, 1, 1)

        self.btn_c_negative = QPushButton(self.gridLayoutWidget_3)
        self.btn_c_negative.setObjectName(u"btn_c_negative")
        palette18 = QPalette()
        palette18.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette18.setBrush(QPalette.Active, QPalette.Text, brush)
        palette18.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette18.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette18.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette18.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette18.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette18.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette18.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette18.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette18.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_c_negative.setPalette(palette18)
        self.btn_c_negative.setFont(font5)
        self.btn_c_negative.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_c_negative, 8, 2, 1, 1)

        self.btn_a_negative = QPushButton(self.gridLayoutWidget_3)
        self.btn_a_negative.setObjectName(u"btn_a_negative")
        palette19 = QPalette()
        palette19.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette19.setBrush(QPalette.Active, QPalette.Text, brush)
        palette19.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette19.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette19.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette19.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette19.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette19.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette19.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette19.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette19.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette19.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette19.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_a_negative.setPalette(palette19)
        self.btn_a_negative.setFont(font5)
        self.btn_a_negative.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_a_negative, 6, 2, 1, 1)

        self.pushButton = QPushButton(self.gridLayoutWidget_3)
        self.pushButton.setObjectName(u"pushButton")

        self.gridLayout_3.addWidget(self.pushButton, 3, 1, 1, 1)

        self.btn_z_negative = QPushButton(self.gridLayoutWidget_3)
        self.btn_z_negative.setObjectName(u"btn_z_negative")
        palette20 = QPalette()
        palette20.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette20.setBrush(QPalette.Active, QPalette.Text, brush)
        palette20.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette20.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette20.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette20.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette20.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette20.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette20.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_z_negative.setPalette(palette20)
        self.btn_z_negative.setFont(font5)
        self.btn_z_negative.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_z_negative, 5, 2, 1, 1)

        self.btn_y_negative = QPushButton(self.gridLayoutWidget_3)
        self.btn_y_negative.setObjectName(u"btn_y_negative")
        palette21 = QPalette()
        palette21.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette21.setBrush(QPalette.Active, QPalette.Text, brush)
        palette21.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette21.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette21.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette21.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette21.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette21.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette21.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette21.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette21.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette21.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette21.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_y_negative.setPalette(palette21)
        self.btn_y_negative.setFont(font5)
        self.btn_y_negative.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_y_negative, 3, 2, 1, 1)

        self.btn_c_positive = QPushButton(self.gridLayoutWidget_3)
        self.btn_c_positive.setObjectName(u"btn_c_positive")
        palette22 = QPalette()
        palette22.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette22.setBrush(QPalette.Active, QPalette.Text, brush)
        palette22.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette22.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette22.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette22.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette22.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette22.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette22.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette22.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette22.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette22.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette22.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_c_positive.setPalette(palette22)
        self.btn_c_positive.setFont(font5)
        self.btn_c_positive.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_c_positive, 8, 0, 1, 1)

        self.btn_b_negative = QPushButton(self.gridLayoutWidget_3)
        self.btn_b_negative.setObjectName(u"btn_b_negative")
        palette23 = QPalette()
        palette23.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette23.setBrush(QPalette.Active, QPalette.Text, brush)
        palette23.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette23.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette23.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette23.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette23.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette23.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette23.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_b_negative.setPalette(palette23)
        self.btn_b_negative.setFont(font5)
        self.btn_b_negative.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_b_negative, 7, 2, 1, 1)

        self.btn_y_positive = QPushButton(self.gridLayoutWidget_3)
        self.btn_y_positive.setObjectName(u"btn_y_positive")
        palette24 = QPalette()
        palette24.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette24.setBrush(QPalette.Active, QPalette.Text, brush)
        palette24.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette24.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette24.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette24.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette24.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette24.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette24.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette24.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette24.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette24.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette24.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_y_positive.setPalette(palette24)
        self.btn_y_positive.setFont(font5)
        self.btn_y_positive.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_y_positive, 3, 0, 1, 1)

        self.btn_x_positive = QPushButton(self.gridLayoutWidget_3)
        self.btn_x_positive.setObjectName(u"btn_x_positive")
        palette25 = QPalette()
        palette25.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Active, QPalette.Button, brush11)
        palette25.setBrush(QPalette.Active, QPalette.Text, brush)
        palette25.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette25.setBrush(QPalette.Active, QPalette.Base, brush11)
        palette25.setBrush(QPalette.Active, QPalette.Window, brush11)
        palette25.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette25.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette25.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette25.setBrush(QPalette.Inactive, QPalette.Base, brush11)
        palette25.setBrush(QPalette.Inactive, QPalette.Window, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette25.setBrush(QPalette.Disabled, QPalette.Button, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette25.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette25.setBrush(QPalette.Disabled, QPalette.Base, brush11)
        palette25.setBrush(QPalette.Disabled, QPalette.Window, brush11)
        self.btn_x_positive.setPalette(palette25)
        self.btn_x_positive.setFont(font5)
        self.btn_x_positive.setStyleSheet(u"background-color:#003060;color:white;border-color: black;")

        self.gridLayout_3.addWidget(self.btn_x_positive, 2, 1, 1, 1)

        self.pushButton_2 = QPushButton(self.gridLayoutWidget_3)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.gridLayout_3.addWidget(self.pushButton_2, 5, 1, 1, 1)

        self.comboBox_jogging_mode = QComboBox(self.gridLayoutWidget_3)
        self.comboBox_jogging_mode.setObjectName(u"comboBox_jogging_mode")

        self.gridLayout_3.addWidget(self.comboBox_jogging_mode, 1, 1, 1, 2)

        self.label_jogging = QLabel(self.gridLayoutWidget_3)
        self.label_jogging.setObjectName(u"label_jogging")

        self.gridLayout_3.addWidget(self.label_jogging, 1, 0, 1, 1)

        self.verticalLayoutWidget_2 = QWidget(self.tab)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(550, 260, 131, 151))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.lcdNumber = QLCDNumber(self.verticalLayoutWidget_2)
        self.lcdNumber.setObjectName(u"lcdNumber")

        self.verticalLayout_2.addWidget(self.lcdNumber)

        self.btn_start_time = QPushButton(self.verticalLayoutWidget_2)
        self.btn_start_time.setObjectName(u"btn_start_time")

        self.verticalLayout_2.addWidget(self.btn_start_time)

        self.btn_stop_time = QPushButton(self.verticalLayoutWidget_2)
        self.btn_stop_time.setObjectName(u"btn_stop_time")

        self.verticalLayout_2.addWidget(self.btn_stop_time)

        self.btn_reset_time = QPushButton(self.verticalLayoutWidget_2)
        self.btn_reset_time.setObjectName(u"btn_reset_time")

        self.verticalLayout_2.addWidget(self.btn_reset_time)

        self.tabWidget.addTab(self.tab, "")
        self.tab_other = QWidget()
        self.tab_other.setObjectName(u"tab_other")
        self.label_arm_picture = QLabel(self.tab_other)
        self.label_arm_picture.setObjectName(u"label_arm_picture")
        self.label_arm_picture.setGeometry(QRect(20, 80, 151, 141))
        self.label_arm_picture.setPixmap(QPixmap(u"../picture/teco_arm.png"))
        self.label_arm_picture.setScaledContents(True)
        self.label_Coordinate_configuration = QLabel(self.tab_other)
        self.label_Coordinate_configuration.setObjectName(u"label_Coordinate_configuration")
        self.label_Coordinate_configuration.setGeometry(QRect(190, 40, 331, 431))
        self.label_Coordinate_configuration.setPixmap(QPixmap(u"../picture/Coordinate_system_configuration_2.jpg"))
        self.label_Coordinate_configuration.setScaledContents(True)
        self.label_other_armshow = QLabel(self.tab_other)
        self.label_other_armshow.setObjectName(u"label_other_armshow")
        self.label_other_armshow.setGeometry(QRect(10, 0, 411, 41))
        palette26 = QPalette()
        brush12 = QBrush(QColor(143, 89, 2, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette26.setBrush(QPalette.Active, QPalette.WindowText, brush12)
        palette26.setBrush(QPalette.Active, QPalette.Text, brush12)
        palette26.setBrush(QPalette.Active, QPalette.ButtonText, brush12)
        palette26.setBrush(QPalette.Inactive, QPalette.WindowText, brush12)
        palette26.setBrush(QPalette.Inactive, QPalette.Text, brush12)
        palette26.setBrush(QPalette.Inactive, QPalette.ButtonText, brush12)
        palette26.setBrush(QPalette.Disabled, QPalette.WindowText, brush10)
        palette26.setBrush(QPalette.Disabled, QPalette.Text, brush10)
        palette26.setBrush(QPalette.Disabled, QPalette.ButtonText, brush10)
        self.label_other_armshow.setPalette(palette26)
        font9 = QFont()
        font9.setFamily(u"DejaVu Sans Mono")
        font9.setPointSize(14)
        font9.setBold(True)
        font9.setWeight(75)
        self.label_other_armshow.setFont(font9)
        self.label_arm_gif = QLabel(self.tab_other)
        self.label_arm_gif.setObjectName(u"label_arm_gif")
        self.label_arm_gif.setGeometry(QRect(30, 280, 151, 141))
        self.label_arm_gif.setPixmap(QPixmap(u"src/modbus/modbus/picture/teco_arm.png"))
        self.label_arm_gif.setScaledContents(True)
        self.tabWidget.addTab(self.tab_other, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 929, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"TECO Arm Modbus Control Window", None))
        self.btn_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.btn_enable.setText(QCoreApplication.translate("MainWindow", u"Enable", None))
        self.btn_disable.setText(QCoreApplication.translate("MainWindow", u"Disable", None))
        self.onBtn.setText(QCoreApplication.translate("MainWindow", u"Read state", None))
        self.offBtn.setText(QCoreApplication.translate("MainWindow", u"Read off", None))
        self.lineEdit_ip.setText(QCoreApplication.translate("MainWindow", u"192.168.0.6", None))
        self.label_ip.setText(QCoreApplication.translate("MainWindow", u"Preset IP:192.168.0.6", None))
        self.btn_ip_set.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
#if QT_CONFIG(whatsthis)
        self.tabWidget.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>dd</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.label_acs_command_list.setText(QCoreApplication.translate("MainWindow", u"Joint Space (ACS)", None))
        self.label_pcs_command_list.setText(QCoreApplication.translate("MainWindow", u"Cartesian Space (PCS)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_arm), QCoreApplication.translate("MainWindow", u"Arm position", None))
        self.label_mission_case_show.setText(QCoreApplication.translate("MainWindow", u"???", None))
        self.label_mission_case.setText(QCoreApplication.translate("MainWindow", u"You choose ?", None))
        self.btn_start_program.setText(QCoreApplication.translate("MainWindow", u"Start task", None))
        self.btn_stop_program.setText(QCoreApplication.translate("MainWindow", u"Stop motion", None))
        self.groupBox_speed.setTitle(QCoreApplication.translate("MainWindow", u"Overall speed setting", None))
        self.btn_acc_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.btn_vel_set.setText(QCoreApplication.translate("MainWindow", u"Set", None))
        self.label_velocity.setText(QCoreApplication.translate("MainWindow", u"Velocity", None))
        self.label_acceleration.setText(QCoreApplication.translate("MainWindow", u"Acceleration", None))
        self.btn_vel_slow_set.setText(QCoreApplication.translate("MainWindow", u"SLOW", None))
        self.btn_vel_quick_set.setText(QCoreApplication.translate("MainWindow", u"QUICK", None))
        self.label_project_name.setText(QCoreApplication.translate("MainWindow", u"Project Name:", None))
        self.btn_project_name_select.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.btn_project_name_read.setText(QCoreApplication.translate("MainWindow", u"Read", None))
        self.btn_show_program.setText(QCoreApplication.translate("MainWindow", u"show 1", None))
        self.btn_dance_program.setText(QCoreApplication.translate("MainWindow", u"show 2", None))
        self.btn_smile_program.setText(QCoreApplication.translate("MainWindow", u"smile", None))
        self.btn_bow_program.setText(QCoreApplication.translate("MainWindow", u"bow", None))
        self.btn_init_program.setText(QCoreApplication.translate("MainWindow", u"init", None))
        self.btn_home_program.setText(QCoreApplication.translate("MainWindow", u"home", None))
        self.btn_stopshow_program.setText(QCoreApplication.translate("MainWindow", u"stop mission", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mission), QCoreApplication.translate("MainWindow", u"Mission", None))
        self.label_rostopic_pub_list.setText(QCoreApplication.translate("MainWindow", u"rostopic /reply_external_comm", None))
        self.label_rostopic_echo_list.setText(QCoreApplication.translate("MainWindow", u"rostopic /write_external_comm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_state), QCoreApplication.translate("MainWindow", u"Message", None))
        self.btn_test.setText(QCoreApplication.translate("MainWindow", u"test", None))
        self.btn_test2.setText(QCoreApplication.translate("MainWindow", u"test2", None))
        self.btn_b_positive.setText(QCoreApplication.translate("MainWindow", u"+B", None))
        self.btn_z_positive.setText(QCoreApplication.translate("MainWindow", u"+Z", None))
        self.btn_x_negative.setText(QCoreApplication.translate("MainWindow", u"-X", None))
        self.btn_a_positive.setText(QCoreApplication.translate("MainWindow", u"+A", None))
        self.btn_c_negative.setText(QCoreApplication.translate("MainWindow", u"-C", None))
        self.btn_a_negative.setText(QCoreApplication.translate("MainWindow", u"-A", None))
        self.pushButton.setText("")
        self.btn_z_negative.setText(QCoreApplication.translate("MainWindow", u"-Z", None))
        self.btn_y_negative.setText(QCoreApplication.translate("MainWindow", u"-Y", None))
        self.btn_c_positive.setText(QCoreApplication.translate("MainWindow", u"+C", None))
        self.btn_b_negative.setText(QCoreApplication.translate("MainWindow", u"-B", None))
        self.btn_y_positive.setText(QCoreApplication.translate("MainWindow", u"+Y", None))
        self.btn_x_positive.setText(QCoreApplication.translate("MainWindow", u"+X", None))
        self.pushButton_2.setText("")
        self.label_jogging.setText(QCoreApplication.translate("MainWindow", u"Jogging", None))
        self.btn_start_time.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_stop_time.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_reset_time.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Jog", None))
        self.label_arm_picture.setText("")
        self.label_Coordinate_configuration.setText("")
        self.label_other_armshow.setText(QCoreApplication.translate("MainWindow", u"Arm coordinate system configuration", None))
        self.label_arm_gif.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_other), QCoreApplication.translate("MainWindow", u"Other", None))
    # retranslateUi

