# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_reload = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reload.setGeometry(QtCore.QRect(140, 110, 89, 25))
        self.btn_reload.setObjectName("btn_reload")
        self.label_reload_state = QtWidgets.QLabel(self.centralwidget)
        self.label_reload_state.setGeometry(QtCore.QRect(480, 90, 81, 20))
        self.label_reload_state.setObjectName("label_reload_state")
        self.btn_enable = QtWidgets.QPushButton(self.centralwidget)
        self.btn_enable.setGeometry(QtCore.QRect(10, 110, 89, 25))
        self.btn_enable.setObjectName("btn_enable")
        self.label_safety_state = QtWidgets.QLabel(self.centralwidget)
        self.label_safety_state.setGeometry(QtCore.QRect(480, 50, 101, 20))
        self.label_safety_state.setObjectName("label_safety_state")
        self.btn_disable = QtWidgets.QPushButton(self.centralwidget)
        self.btn_disable.setGeometry(QtCore.QRect(10, 170, 89, 25))
        self.btn_disable.setObjectName("btn_disable")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(10, 30, 89, 25))
        self.btn_reset.setObjectName("btn_reset")
        self.label_reset = QtWidgets.QLabel(self.centralwidget)
        self.label_reset.setGeometry(QtCore.QRect(20, 10, 67, 17))
        self.label_reset.setObjectName("label_reset")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 170, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(480, 210, 67, 17))
        self.label_6.setObjectName("label_6")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(140, 170, 89, 25))
        self.btn_start.setObjectName("btn_start")
        self.label_task_state = QtWidgets.QLabel(self.centralwidget)
        self.label_task_state.setGeometry(QtCore.QRect(480, 130, 67, 17))
        self.label_task_state.setObjectName("label_task_state")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_reload.setText(_translate("MainWindow", "reload"))
        self.label_reload_state.setText(_translate("MainWindow", "reload"))
        self.btn_enable.setText(_translate("MainWindow", "enable"))
        self.label_safety_state.setText(_translate("MainWindow", "safety state"))
        self.btn_disable.setText(_translate("MainWindow", "disable"))
        self.btn_reset.setText(_translate("MainWindow", "check"))
        self.label_reset.setText(_translate("MainWindow", "reset"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.btn_start.setText(_translate("MainWindow", "start"))
        self.label_task_state.setText(_translate("MainWindow", "task state"))
